/* ============================================================
   COMBINED PLAYER + HOST UI
   ============================================================ */
(function(){
'use strict';
const cfg=window.KA_PLAYER_CONFIG||{}; if(!cfg.format||!window.KA_SB)return;
const sb=window.KA_SB; const format=cfg.format; let state=null; let myName=sessionStorage.getItem('ka_player_'+format)||'';
const q=s=>document.querySelector(s);
function esc(s){const d=document.createElement('div');d.textContent=String(s||'');return d.innerHTML;}
function table(){return cfg.table;}
async function read(){const r=await sb.from(table()).select('*').eq('id',cfg.id||1).single(); if(!r.error)state=r.data?.[cfg.column||'state']||r.data?.state||r.data?.data||{}; return state;}
function score(){if(!state)return 0; if(cfg.scoreType==='array'){const p=(state.players||[]).find(x=>x.name===myName);return p?Number(p.score||0):0;} const v=(state.players||{})[myName]; if(typeof v==='number')return v; return Number(v?.score||0);}
function pointsLabel(){return cfg.scoreLabel==='LEBEN'?((state?.players||[]).find(p=>p.name===myName)?.lives||0)+' ♥':score()+' P';}
async function save(s){const patch={};patch[cfg.column||'state']=s;patch.updated_at=new Date().toISOString();return sb.from(table()).update(patch).eq('id',cfg.id||1);}
function inject(){if(document.getElementById('kaPlayerPanel'))return;const st=document.createElement('style');st.id='kaPlayerPanelStyle';st.textContent=`
.ka-combined{position:fixed;left:18px;bottom:18px;z-index:9900;width:min(350px,calc(100vw - 36px));padding:14px;border:1px solid rgba(255,255,255,.12);border-radius:22px;background:rgba(8,12,23,.94);backdrop-filter:blur(18px);box-shadow:0 20px 70px rgba(0,0,0,.45);font-family:Inter,system-ui,sans-serif;color:#eef1f8}.ka-combined h3{margin:0 0 10px;font-size:12px;letter-spacing:.12em;text-transform:uppercase}.ka-combined input{width:100%;padding:12px;border-radius:12px;border:1px solid #2b3655;background:#11182a;color:#fff;outline:none}.ka-combined .ka-row{display:flex;gap:8px;align-items:center}.ka-combined button{border:0;border-radius:12px;padding:12px 14px;background:#18223a;color:#fff;font-weight:900;cursor:pointer}.ka-combined button.primary{background:linear-gradient(135deg,#00e5c7,#5a78fa);color:#04120f}.ka-combined button:disabled{opacity:.4;cursor:not-allowed}.ka-combined .ka-video{width:100%;aspect-ratio:16/9;object-fit:cover;border-radius:15px;background:#05070d;margin:8px 0}.ka-combined .ka-name{font-weight:900}.ka-combined .ka-points{margin-left:auto;color:#00e5c7;font-weight:900}.ka-combined .ka-status{font-size:11px;color:#8b96ad;margin:7px 0}.ka-stream-mode .ka-combined{display:none!important}
`;document.head.appendChild(st);const p=document.createElement('aside');p.id='kaPlayerPanel';p.className='ka-combined';document.body.appendChild(p);renderPanel();}
function renderPanel(){const p=q('#kaPlayerPanel');if(!p)return;if(!myName){p.innerHTML='<h3>Dein Spieler</h3><input id="kaName" maxlength="32" placeholder="Dein Name" autocomplete="nickname"><div class="ka-status">Name eingeben und beitreten.</div><button class="primary" id="kaJoin">Beitreten</button>';q('#kaJoin').onclick=join;return;}p.innerHTML=`<h3>Spieler</h3><video class="ka-video" id="kaLocalVideo" autoplay muted playsinline></video><div class="ka-row"><div class="ka-name" id="kaPlayerName">${esc(myName)}</div><div class="ka-points" id="kaPts">${pointsLabel()}</div><span id="kaPlayerScore" hidden></span></div><div class="ka-status"><span id="kaStatus">Spielstatus live</span> · <span id="kaCamStatus">Kamera aus</span></div><div class="ka-row"><button id="kaCamBtn">Kamera aktivieren</button>${cfg.action!=='none'?`<button class="primary" id="kaActionBtn">${cfg.actionLabel||'BUZZ'}</button>`:''}</div>`;const cb=q('#kaCamBtn');if(cb)cb.onclick=()=>{if(window.KA_CAM){if(window.KA_CAM.isOn?.())window.KA_CAM.cameraOff();else window.KA_CAM.cameraOn();}};const kb=q('#kaActionBtn');if(kb)kb.onclick=action;}
async function join(){const n=window.KA_PUBLIC.normalizeName(q('#kaName').value);if(!n)return;const r=await window.KA_PUBLIC.registerPlayer(n,format);if(!r.ok){q('#kaName').focus();return;}myName=n;sessionStorage.setItem('ka_player_'+format,n);await read();await ensurePlayer(r.data?.fresh === true);renderPanel();}
async function ensurePlayer(fresh=false){if(!state)return;if(cfg.scoreType==='array'){let arr=state.players||[];let p=arr.find(x=>x.name===myName);if(!p){state.players=[...arr,{name:myName,lives:3,score:0}];await save(state);}else if(fresh){p.score=0;if('lives' in p)p.lives=3;await save(state);}}else{state.players=state.players||{};if(fresh||state.players[myName]==null){state.players[myName]=0;await save(state);}}}
function canBuzz(){if(!state)return false;if(cfg.action==='queue'){const has=cfg.hasGame?cfg.hasGame(state):true;const qarr=state.buzzQueue||[];return has&&!state.solved&&!qarr.includes(myName)&&!(state.buzzedOut||[]).includes(myName);}if(cfg.action==='hl'){return !!state.category && !!myName && !((state.players||[]).find(p=>p.name===myName)?.lives<=0);}return false;}
async function action(){await read();if(!myName)return; if(cfg.action==='queue'){if(!canBuzz())return;const s=JSON.parse(JSON.stringify(state));s.buzzQueue=s.buzzQueue||[];s.buzzedOut=s.buzzedOut||[];if(s.buzzQueue.includes(myName)||s.buzzedOut.includes(myName))return;s.buzzQueue.push(myName);if(cfg.freeze && s.frozenAt==null)s.frozenAt=Date.now();await save(s);}else if(cfg.action==='hl'){if(!canBuzz())return;const s=JSON.parse(JSON.stringify(state));if(!s.turnName)s.turnName=myName;await save(s);}await read();update();}
function update(){const pts=q('#kaPts'),btn=q('#kaActionBtn'),status=q('#kaStatus');if(pts)pts.textContent=pointsLabel();if(btn)btn.disabled=!canBuzz();if(status){if(!myName)status.textContent='';else if(cfg.action==='queue'){const active=(state?.buzzQueue||[]).find(n=>!(state?.buzzedOut||[]).includes(n));status.textContent=active===myName?'Du bist dran.':active?'Buzzer läuft – warte.':canBuzz()?'Buzzer offen.':'Warte auf die nächste Runde.';}else if(cfg.action==='hl'){status.textContent=state?.turnName===myName?'Du bist dran.':state?.turnName?'Aktuell ist '+state.turnName+' dran.':'Drücke Buzzer für deinen Zug.';}else status.textContent='Spiel läuft.';}}
function poll(){read().then(()=>{if(myName)update();});}
async function boot(){if(new URLSearchParams(location.search).get('stream')==='1'){document.documentElement.classList.add('ka-stream-mode');document.body.classList.add('ka-stream-mode');if(window.KA_CAM)window.KA_CAM.init({format,role:'stream'});return;}inject();if(myName){await read();await ensurePlayer();renderPanel();}setInterval(poll,1000);}
window.KA_PLAYER_HOST={score,action,format};boot();
})();
