const SITUATIONEN = [
  "Du kommst um 4 Uhr morgens nach Hause. Deine Mutter steht in der Küche.",
  "Du hast das Meeting verpasst, in dem du präsentieren solltest.",
  "Der Kuchen deiner Grossmutter ist leer, bevor die Gäste kommen.",
  "Du hast dem Chef aus Versehen eine Sprachnachricht geschickt.",
  "Die Polizei hält dich an. Auf dem Rücksitz liegen zwölf Gartenzwerge.",
  "Du hast den Geburtstag deiner besten Freundin vergessen.",
  "Dein Nachbar findet seinen Rasenmäher in deinem Keller.",
  "Du wachst in einem fremden Bus in einer fremden Stadt auf.",
  "Die Prüfungsaufsicht sieht Notizen auf deinem Handgelenk.",
  "Du kommst mit einem Auge zugeklebt zum Bewerbungsgespräch.",
  "Der Vermieter steht vor der Tür. Im Flur steht ein Pony.",
  "Du hast alle Snacks aufgegessen, die für die Party gedacht waren.",
  "Dein Trainer fragt, warum du drei Wochen nicht im Training warst.",
  "Du sitzt in der falschen Vorlesung und wirst aufgerufen.",
  "Die Rechnung im Restaurant kommt. Dein Portemonnaie ist leer.",
  "Du hast das Auto deines Vaters mit leerem Tank zurückgebracht.",
  "Auf deinem Bildschirm läuft im Videocall etwas sehr Falsches.",
  "Du wirst dabei erwischt, wie du den Kühlschrank im Büro leerräumst.",
  "Dein Hund hat die Hausaufgaben deiner Schwester gefressen.",
  "Du kommst zwei Stunden zu spät zur eigenen Überraschungsparty.",
  "Der Zugbegleiter fragt nach deinem Ticket. Du hast keins.",
  "Dein Kumpel fragt, wo die 200 Franken sind, die er dir geliehen hat.",
  "Du hast die Pflanze deiner Mitbewohnerin komplett eingehen lassen.",
  "Im Fitnessstudio bricht das Gerät, an dem du sitzt.",
  "Du hast versehentlich die Gruppennachricht an die falsche Gruppe geschickt.",
  "Deine Freundin findet ein zweites Handy in deiner Jacke.",
  "Du stehst um Mitternacht im Supermarkt in Badeschlappen und Anzugjacke.",
  "Der Lehrer fragt, warum dein Aufsatz wortwörtlich dem deines Sitznachbarn gleicht.",
  "Du hast das Hochzeitsgeschenk im Zug liegen gelassen.",
  "Die Katze deiner Nachbarin sitzt seit drei Tagen in deiner Wohnung.",
  "Du wirst gefragt, warum du beim Videocall die Kamera nie anmachst.",
  "Am Flughafen fragt der Zoll, was in deinem Koffer klappert.",
  "Du hast den letzten Kaffee genommen und die Kanne nicht neu aufgesetzt.",
  "Dein Bruder fragt, wo sein Lieblingspullover geblieben ist.",
  "Du bist auf einem Foto zu sehen, wo du eigentlich krank sein solltest.",
  "Der Kellner bringt eine Rechnung über 340 Franken für Getränke.",
  "Du hast beim Umzug die Kiste mit dem Porzellan fallen lassen.",
  "Deine Mitbewohner fragen, warum die Waschmaschine nach Fisch riecht.",
  "Du hast im Gruppenprojekt nichts gemacht und wirst nach deinem Teil gefragt.",
  "Der Hausmeister fragt, warum der Feueralarm um 3 Uhr losging.",
  "Du kommst mit Grasflecken und einem Schuh nach Hause.",
  "Die Nachbarn beschweren sich über Karaoke um zwei Uhr nachts.",
  "Du hast das Passwort für den gemeinsamen Account geändert.",
  "Deine Tante fragt, warum du ihre Anrufe seit Monaten wegdrückst.",
  "Im Kino klingelt dein Handy während der leisesten Szene.",
  "Du hast versehentlich das Bild deines Chefs kommentiert.",
  "Der Paketbote fragt, warum du sieben Pakete am Tag bekommst.",
  "Du sitzt im Bewerbungsgespräch und dein Magen macht Geräusche.",
  "Deine Schwester findet ihr Tagebuch aufgeschlagen auf deinem Bett.",
  "Du hast beim Grillen das Fleisch aller Gäste verbrennen lassen.",
  "Der Zahnarzt fragt, wann du zuletzt Zahnseide benutzt hast.",
  "Du kommst zur Beerdigung in einem knallgelben Anzug.",
  "Dein Team fragt, warum der Server seit gestern offline ist.",
  "Du hast die Fernbedienung so versteckt, dass du sie selbst nicht findest.",
  "Die Kassiererin fragt, warum die Packung Kekse geöffnet ist.",
  "Du wirst gefragt, warum du auf der Hochzeit alleine getanzt hast.",
  "Dein Kollege fragt, warum sein Mittagessen im Kühlschrank fehlt.",
  "Du hast dich im Videocall vergessen stummzuschalten und geschimpft.",
  "Die Schulleitung fragt, warum ein Schaf im Klassenzimmer steht.",
  "Du kommst mit einer neuen Frisur nach Hause, die niemand erwartet hat.",
  "Beim Wandern verlierst du die Karte und behauptest, du kennst den Weg.",
  "Dein Chef fragt, warum du im Homeoffice nie erreichbar bist.",
  "Du wirst beim Klauen von Blumen aus dem Nachbargarten erwischt.",
  "Der Freund fragt, warum sein Spiel zerkratzt zurückkommt.",
  "Du sitzt im falschen Flugzeug und bemerkst es beim Start.",
  "Deine Mutter findet deinen Kontoauszug auf dem Küchentisch.",
  "Du hast das Netflix-Finale ohne deinen Partner geschaut.",
  "Der Vermieter fragt, warum ein Loch in der Wand ist.",
  "Du kommst zur Prüfung ohne Stift, Ausweis und Uhr.",
  "Dein Nachbar fragt, warum seine Post bei dir landet.",
  "Du hast die Playlist für die Party gemacht und alle gehen früh.",
  "Die Freundin fragt, warum du ihren Namen falsch geschrieben hast.",
  "Du wirst gefragt, warum du drei Wecker stellst und trotzdem verschläfst.",
  "Im Zoo fragt der Wärter, warum du hinter der Absperrung stehst.",
  "Du hast beim Kochen die Küche unter Wasser gesetzt.",
  "Dein Kumpel fragt, warum du seinen Geburtstag doppelt gefeiert hast.",
  "Die Bank fragt, wofür die Abhebung um 3 Uhr morgens war.",
  "Du kommst mit dem Fahrrad deines Nachbarn nach Hause.",
  "Der Trainer fragt, warum du im Spiel in die falsche Richtung gelaufen bist.",
  "Du hast das WLAN-Passwort an die halbe Nachbarschaft weitergegeben.",
  "Deine Eltern fragen, warum ein Tattoo auf deinem Arm ist.",
  "Du wirst gefragt, warum du beim Escape Room die Tür eingetreten hast.",
  "Der Kellner fragt, warum ihr das Besteck einpackt.",
  "Du hast beim Umzug das Sofa im Treppenhaus stecken lassen.",
  "Deine Mitbewohnerin fragt, warum ihr Shampoo halb leer ist.",
  "Du kommst zum Vorstellungsgespräch in der Jogginghose.",
  "Der Nachbar fragt, warum sein Auto anders parkt als gestern Abend.",
  "Du hast auf dem Konzert das Ticket verloren und stehst draussen.",
  "Deine Freunde fragen, warum du in den Ferien nie geantwortet hast.",
  "Du wirst dabei ertappt, wie du im Büro schläfst.",
  "Der Busfahrer fragt, warum du ohne Schuhe einsteigst.",
  "Du hast versehentlich das falsche Geschenk übergeben.",
  "Dein Team fragt, warum die Präsentation nur aus einer Folie besteht.",
  "Die Nachbarin fragt, warum ihr Gartenzaun umgefallen ist.",
  "Du kommst vom Einkaufen zurück ohne einen einzigen Artikel von der Liste.",
  "Der Dozent fragt, warum du seit Wochen nicht in der Vorlesung warst.",
  "Du hast die Grillkohle im Wohnzimmer angezündet.",
  "Dein Partner fragt, warum das Auto nach Pommes riecht.",
  "Du wirst gefragt, warum du die Party um 21 Uhr verlassen hast.",
  "Die Wirtin fragt, warum ein Stuhl fehlt.",
  "Du hast im Museum ein Absperrband gerissen.",
  "Du stehst um 3 Uhr nachts in der Küche deines Nachbarn. Er macht das Licht an.",
  "Dein Chef findet heraus, dass du seit zwei Wochen im falschen Büro sitzt.",
  "Du hast das Auto deines Vaters zurückgebracht. Es ist jetzt gelb.",
  "Die Bibliothekarin fragt nach dem Buch, das du vor sechs Jahren ausgeliehen hast.",
  "Du wirst beim Verlassen des Supermarkts mit einem Einkaufswagen voller Kerzen angehalten.",
  "Dein Zahnarzt fragt, warum du zwei Termine hintereinander verpasst hast.",
  "Du kommst mit einer Schubkarre zur Hochzeit deiner Cousine.",
  "Der Busfahrer fragt, warum du seit vier Stunden im Bus sitzt.",
  "Deine Vermieterin findet ein Hochbett auf dem Balkon.",
  "Du wirst dabei erwischt, wie du die Blumen im Büro fütterst.",
  "Dein Trainer sieht dich am Spieltag im Trikot der Gegner.",
  "Du hast versehentlich der ganzen Firma statt nur deinem Kollegen geantwortet.",
  "Die Sicherheitskontrolle findet drei Kilo Käse in deinem Handgepäck.",
  "Du sitzt in einem Meeting, zu dem du gar nicht eingeladen warst.",
  "Deine Schwester findet ihr Auto komplett mit Post-its beklebt.",
  "Du erklärst, warum der Weihnachtsbaum im Februar noch steht.",
  "Der Kellner fragt, warum du die Speisekarte einsteckst.",
  "Du wirst nachts im Zoo gefunden, mit einer Tüte Karotten.",
  "Dein Mitbewohner fragt, warum die Badewanne voller Sand ist.",
  "Der Postbote fragt, warum du seit Wochen jeden Tag ein Paket zurückschickst.",
  "Du erklärst der Feuerwehr, warum der Toaster im Garten steht.",
  "Deine Grossmutter fragt, warum ihr Gebiss im Kühlschrank liegt.",
  "Du kommst mit nassen Haaren und ohne Schuhe ins Vorstellungsgespräch.",
  "Der Nachbar fragt, warum seine Gartenzwerge alle Richtung Osten schauen.",
  "Du wirst dabei erwischt, wie du am Bankautomaten mit ihm redest.",
  "Deine Freundin findet 40 identische T-Shirts in deinem Schrank.",
  "Der Fahrlehrer fragt, warum du rückwärts in die Autobahn gefahren bist.",
  "Du erklärst, warum in deiner Waschmaschine ein Fahrradreifen liegt.",
  "Der Kassierer fragt, warum du nur mit Münzen bezahlst.",
  "Du wirst gefragt, warum du zur Beerdigung ein Hawaiihemd trägst.",
  "Deine Mutter findet einen Vertrag über ein Alpaka in deiner Schublade.",
  "Du sitzt im Kino, aber der Film läuft schon seit einer Stunde.",
  "Der Schaffner fragt, warum dein Ticket auf «Bruce Wayne» ausgestellt ist.",
  "Du erklärst dem Hausmeister, warum der Aufzug nach Popcorn riecht.",
  "Dein Kollege fragt, warum sein Bürostuhl auf dem Dach steht.",
  "Du wirst gefragt, warum du im Fitnessstudio nur die Spiegel putzt.",
  "Der Bademeister fragt, warum du in voller Kleidung ins Becken gesprungen bist.",
  "Deine Freunde fragen, warum du drei Handys gleichzeitig benutzt.",
  "Du erklärst, warum du eine Leiter zum Bewerbungsgespräch mitgebracht hast.",
  "Der Tierarzt fragt, warum dein Hund grün ist.",
  "Du wirst im Baumarkt beim Testen aller Türklingeln erwischt.",
  "Deine Nachbarin fragt, warum ihr Briefkasten in deinem Wohnzimmer hängt.",
  "Der Lehrer fragt, warum du das Referat auf einer Serviette geschrieben hast.",
  "Du erklärst, warum du im Restaurant dein eigenes Besteck ausgepackt hast.",
  "Der Chef fragt, warum du das Firmenlogo geändert hast.",
  "Du wirst gefragt, warum du im Zug laut Nachrichten vorliest.",
  "Deine Freundin findet eine Rechnung über 200 Franken für Gummienten.",
  "Du erklärst, warum du seit einer Woche rückwärts läufst.",
  "Der Concierge fragt, warum du im Hotel dein eigenes Bett aufgebaut hast.",
  "Du wirst gefragt, warum du beim Bewerbungsgespräch die Pflanzen giesst.",
  "Dein Bruder fragt, warum seine Playstation im Gefrierfach liegt.",
  "Du erklärst, warum du im Supermarkt die Regale umgeräumt hast.",
  "Der Kollege fragt, warum du auf allen Fotos jemand anderes bist.",
  "Du wirst gefragt, warum du zum Vorstellungsgespräch dein Haustier mitgebracht hast.",
  "Deine Vermieterin findet einen zweiten Kühlschrank im Schlafzimmer.",
  "Du erklärst, warum die Nachbarskatze deinen Hausschlüssel hat.",
  "Der Busfahrer fragt, warum du jeden Tag zwei Stationen zu früh aussteigst.",
  "Du wirst gefragt, warum du beim Zahnarzt eingeschlafen bist und geschnarcht hast.",
  "Der Trainer fragt, warum du beim Marathon ein Fahrrad dabei hattest.",
  "Deine Mutter fragt, warum das Sofa jetzt im Garten steht.",
  "Du erklärst, warum du im Büro eine Hängematte aufgehängt hast.",
  "Der Nachbar fragt, warum du nachts seinen Rasen mähst.",
  "Du wirst gefragt, warum du beim Kinobesuch eine Pizza geliefert bekommen hast.",
  "Deine Kollegin fragt, warum ihr Namensschild jetzt an deiner Tür hängt.",
  "Du erklärst, warum dein Fahrrad im dritten Stock steht.",
  "Der Kellner fragt, warum du das Salz mitgenommen hast.",
  "Du wirst gefragt, warum du im Museum die Bilder umgehängt hast.",
  "Deine Familie fragt, warum du Weihnachten alleine im Auto verbracht hast.",
  "Du erklärst, warum du zum Camping einen Fernseher mitgenommen hast.",
  "Der Zöllner fragt, warum du 60 Packungen Kaugummi dabei hast.",
  "Du wirst gefragt, warum du in der Bibliothek telefonierst.",
  "Dein Chef fragt, warum du die Kaffeemaschine mit nach Hause genommen hast.",
  "Du erklärst, warum du im Aufzug jedes Stockwerk gedrückt hast.",
  "Deine Freundin fragt, warum du ihren Namen falsch tätowiert hast.",
  "Der Nachbar fragt, warum sein Auto voller Blätter ist.",
  "Du wirst gefragt, warum du beim Joggen einen Anzug trägst.",
  "Dein Mitbewohner fragt, warum die Mikrowelle nach Fisch riecht.",
  "Du erklärst, warum du im Flugzeug den Notausgang fotografiert hast.",
  "Der Lehrer fragt, warum du zum Test einen Taschenrechner von 1985 mitgebracht hast.",
  "Du wirst gefragt, warum du im Restaurant zweimal dasselbe bestellt hast.",
  "Deine Grossmutter fragt, warum ihr Fernseher jetzt auf Japanisch läuft.",
  "Du erklärst, warum du im Schwimmbad Socken trägst.",
  "Der Kollege fragt, warum du seinen Stuhl höher gestellt hast.",
  "Du wirst gefragt, warum du zum Elternabend verkleidet erschienen bist.",
  "Deine Schwester fragt, warum ihr Zimmer nach Knoblauch riecht.",
  "Du erklärst, warum du beim Zelten das Zelt vergessen hast.",
  "Der Wirt fragt, warum du dein eigenes Glas mitgebracht hast.",
  "Du wirst gefragt, warum du seit gestern nur noch flüsterst.",
  "Deine Nachbarin fragt, warum ihre Wäsche jetzt rosa ist.",
  "Du erklärst, warum im Kofferraum ein Karton voller Schnee liegt.",
  "Der Chef fragt, warum in der Präsentation Urlaubsfotos waren.",
  "Du wirst gefragt, warum du beim Frisör eingeschlafen bist und nun eine Glatze hast.",
  "Deine Freunde fragen, warum du zum Grillen einen Toaster mitgebracht hast.",
  "Du erklärst, warum das WLAN-Passwort jetzt dein Vorname ist.",
  "Der Nachbar fragt, warum sein Gartenschlauch in deinem Baum hängt.",
  "Du wirst gefragt, warum du beim Bewerbungsgespräch die Stelle des Chefs verlangt hast.",
  "Deine Mutter fragt, warum das Katzenklo im Wohnzimmer steht.",
  "Du erklärst, warum du im Kino in der ersten Reihe geschlafen hast.",
  "Der Kollege fragt, warum sein Passwort jetzt auf einem Post-it klebt.",
  "Du wirst gefragt, warum du im Zug fremde Leute geweckt hast.",
  "Deine Vermieterin fragt, warum die Tür anders herum eingebaut ist."
];

window.SITUATIONEN = SITUATIONEN;
