
const WOERTER = [
  { kategorie: "Peinlich", wort: "Leberfleck" },
  { kategorie: "Peinlich", wort: "Fussschweiss" },
  { kategorie: "Peinlich", wort: "Bremsspur" },
  { kategorie: "Peinlich", wort: "Zahnspange" },
  { kategorie: "Peinlich", wort: "Sonnenbrand" },
  { kategorie: "Peinlich", wort: "Ohrenschmalz" },
  { kategorie: "Peinlich", wort: "Furz im Aufzug" },
  { kategorie: "Peinlich", wort: "Rückenhaare" },

  { kategorie: "Tier", wort: "Nacktmull" },
  { kategorie: "Tier", wort: "Faultier" },
  { kategorie: "Tier", wort: "Alpaka" },
  { kategorie: "Tier", wort: "Axolotl" },
  { kategorie: "Tier", wort: "Erdmännchen" },
  { kategorie: "Tier", wort: "Chihuahua" },
  { kategorie: "Tier", wort: "Vogelspinne" },
  { kategorie: "Tier", wort: "Blobfisch" },
  { kategorie: "Tier", wort: "Waschbär" },
  { kategorie: "Tier", wort: "Lama" },

  { kategorie: "Essen", wort: "Döner um 3 Uhr nachts" },
  { kategorie: "Essen", wort: "Ananas auf Pizza" },
  { kategorie: "Essen", wort: "Fischstäbchen" },
  { kategorie: "Essen", wort: "Kalter Kaffee" },
  { kategorie: "Essen", wort: "Rosenkohl" },
  { kategorie: "Essen", wort: "Energy Drink" },
  { kategorie: "Essen", wort: "Mensa-Essen" },
  { kategorie: "Essen", wort: "Blauschimmelkäse" },
  { kategorie: "Essen", wort: "Toastbrot ohne alles" },
  { kategorie: "Essen", wort: "Nudeln mit Ketchup" },

  { kategorie: "Beruf", wort: "Influencer" },
  { kategorie: "Beruf", wort: "Klobrillentester" },
  { kategorie: "Beruf", wort: "Politesse" },
  { kategorie: "Beruf", wort: "Bestatter" },
  { kategorie: "Beruf", wort: "Kammerjäger" },
  { kategorie: "Beruf", wort: "Zoowärter" },
  { kategorie: "Beruf", wort: "Wahrsagerin" },
  { kategorie: "Beruf", wort: "Streamer" },
  { kategorie: "Beruf", wort: "Fahrlehrer" },

  { kategorie: "Ort", wort: "Öffentliche Toilette" },
  { kategorie: "Ort", wort: "Zahnarztstuhl" },
  { kategorie: "Ort", wort: "Umkleidekabine" },
  { kategorie: "Ort", wort: "Nachtbus" },
  { kategorie: "Ort", wort: "Wartezimmer" },
  { kategorie: "Ort", wort: "Fitnessstudio im Januar" },
  { kategorie: "Ort", wort: "Schwimmbad" },
  { kategorie: "Ort", wort: "Sauna" },
  { kategorie: "Ort", wort: "Kellerabteil" },
  { kategorie: "Ort", wort: "Ikea am Samstag" },

  { kategorie: "Gegenstand", wort: "Klopapierrolle" },
  { kategorie: "Gegenstand", wort: "Selfiestick" },
  { kategorie: "Gegenstand", wort: "Ladekabel" },
  { kategorie: "Gegenstand", wort: "Gartenzwerg" },
  { kategorie: "Gegenstand", wort: "Rasierer" },
  { kategorie: "Gegenstand", wort: "Nasenhaartrimmer" },
  { kategorie: "Gegenstand", wort: "Klobürste" },
  { kategorie: "Gegenstand", wort: "Handyhülle" },
  { kategorie: "Gegenstand", wort: "Fliegenklatsche" },
  { kategorie: "Gegenstand", wort: "Schnappmesser" },
  { kategorie: "Gegenstand", wort: "Aufblasbares Einhorn" },

  { kategorie: "Sport", wort: "Bierpong" },
  { kategorie: "Sport", wort: "Völkerball" },
  { kategorie: "Sport", wort: "Sackhüpfen" },
  { kategorie: "Sport", wort: "Bodybuilding" },
  { kategorie: "Sport", wort: "Sumo-Ringen" },
  { kategorie: "Sport", wort: "Klettern" },
  { kategorie: "Sport", wort: "Tischtennis" },
  { kategorie: "Sport", wort: "Schach" },

  { kategorie: "Gaming", wort: "Rage Quit" },
  { kategorie: "Gaming", wort: "Lag" },
  { kategorie: "Gaming", wort: "Noob" },
  { kategorie: "Gaming", wort: "Loot Box" },
  { kategorie: "Gaming", wort: "Speedrun" },
  { kategorie: "Gaming", wort: "Endboss" },
  { kategorie: "Gaming", wort: "Respawn" },
  { kategorie: "Gaming", wort: "AFK" },
  { kategorie: "Gaming", wort: "Camper" },

  { kategorie: "Situation", wort: "Erstes Date" },
  { kategorie: "Situation", wort: "Kater am Morgen" },
  { kategorie: "Situation", wort: "Verschlafen" },
  { kategorie: "Situation", wort: "Klassenfoto" },
  { kategorie: "Situation", wort: "Zahnarzttermin" },
  { kategorie: "Situation", wort: "Umzug" },
  { kategorie: "Situation", wort: "Familienfeier" },
  { kategorie: "Situation", wort: "Bewerbungsgespräch" },
  { kategorie: "Situation", wort: "Elternabend" },
  { kategorie: "Situation", wort: "Blind Date" },

  { kategorie: "Film & Serie", wort: "Horrorfilm" },
  { kategorie: "Film & Serie", wort: "Telenovela" },
  { kategorie: "Film & Serie", wort: "Tierdoku" },
  { kategorie: "Film & Serie", wort: "Werbepause" },
  { kategorie: "Film & Serie", wort: "Reality-TV" },
  { kategorie: "Film & Serie", wort: "Tatort" },
  { kategorie: "Film & Serie", wort: "Weihnachtsfilm" },

  { kategorie: "Körper", wort: "Nasenbluten" },
  { kategorie: "Körper", wort: "Schluckauf" },
  { kategorie: "Körper", wort: "Muskelkater" },
  { kategorie: "Körper", wort: "Zahnlücke" },
  { kategorie: "Körper", wort: "Doppelkinn" },
  { kategorie: "Körper", wort: "Schnarchen" },
  { kategorie: "Körper", wort: "Gänsehaut" },

  { kategorie: "Wetter", wort: "Hagelsturm" },
  { kategorie: "Wetter", wort: "Nieselregen" },
  { kategorie: "Wetter", wort: "Hitzewelle" },
  { kategorie: "Wetter", wort: "Glatteis" },
  { kategorie: "Wetter", wort: "Nebel" },

  { kategorie: "Fahrzeug", wort: "E-Scooter" },
  { kategorie: "Fahrzeug", wort: "Bobbycar" },
  { kategorie: "Fahrzeug", wort: "Traktor" },
  { kategorie: "Fahrzeug", wort: "Heissluftballon" },
  { kategorie: "Fahrzeug", wort: "Müllauto" },
  { kategorie: "Fahrzeug", wort: "U-Boot" },
  { kategorie: "Fahrzeug", wort: "Einkaufswagen" },

  { kategorie: "Musik", wort: "Karaoke" },
  { kategorie: "Musik", wort: "Blockflöte" },
  { kategorie: "Musik", wort: "Ballermann-Hit" },
  { kategorie: "Musik", wort: "Ohrwurm" },
  { kategorie: "Musik", wort: "Dudelsack" },
  { kategorie: "Musik", wort: "Techno" },
  { kategorie: "Musik", wort: "Kirchenchor" },

  { kategorie: "Internet", wort: "Katzenvideo" },
  { kategorie: "Internet", wort: "Spam-Mail" },
  { kategorie: "Internet", wort: "Cookie-Banner" },
  { kategorie: "Internet", wort: "Gruppenchat" },
  { kategorie: "Internet", wort: "Ungelesene Nachricht" },
  { kategorie: "Internet", wort: "Autokorrektur" },
  { kategorie: "Internet", wort: "Passwort vergessen" }
];
