
const BLUFF_FRAGEN = [
  { frage: "In Finnland gibt es tatsächlich eine offizielle Weltmeisterschaft im ___.", antwort: "Ehefrauentragen" },
  { frage: "In Japan gibt es einen Wettbewerb, bei dem man möglichst lange ___ muss.", antwort: "gar nichts tun" },
  { frage: "Eine Gruppe Flamingos nennt man offiziell ___.", antwort: "eine Flamboyance" },
  { frage: "Bevor es Radiergummis gab, radierten die Leute mit ___.", antwort: "altbackenem Brot" },
  { frage: "Der Name «Nintendo» heisst übersetzt ungefähr ___.", antwort: "überlasse das Glück dem Himmel" },
  { frage: "Der teuerste Kaffee der Welt entsteht dadurch, dass die Bohnen vorher ___.", antwort: "von einer Schleichkatze verdaut werden" },
  { frage: "In einer Stadt in Italien ist es verboten, ___.", antwort: "traurig zu sein" },
  { frage: "Astronauten dürfen im All kein normales Brot essen, weil ___.", antwort: "die Krümel in die Geräte fliegen" },
  { frage: "In Schweden gibt es ein Museum, das nur ___ ausstellt.", antwort: "misslungene Produkte" },
  { frage: "Kühe geben nachweislich mehr Milch, wenn man ihnen ___.", antwort: "Musik vorspielt" },
  { frage: "Ein Blauwalherz ist ungefähr so gross wie ___.", antwort: "ein Kleinwagen" },
  { frage: "In Südkorea ist es ein Trend, im Livestream ___ zuzuschauen.", antwort: "anderen beim Essen" },
  { frage: "Die erste Ware, die je online verkauft wurde, war angeblich ___.", antwort: "eine Tüte Gras" },
  { frage: "In der Antarktis gibt es keine ___.", antwort: "Zeitzone" },
  { frage: "Eine Schnecke kann bis zu ___ am Stück schlafen.", antwort: "drei Jahre" },
  { frage: "Der offizielle Rekord im Dauerlachen liegt bei ___.", antwort: "über zwei Stunden" },
  { frage: "In manchen Ländern ist es verboten, ein Schwein ___ zu nennen.", antwort: "Napoleon" },
  { frage: "Bananen sind botanisch gesehen eigentlich ___.", antwort: "Beeren" },
  { frage: "Ein Kolibri muss täglich etwa ___ seines Körpergewichts fressen.", antwort: "die Hälfte" },
  { frage: "In Grossbritannien gibt es eine Meisterschaft im ___.", antwort: "Käserollen den Hügel runter" },
  { frage: "Der längste je gemessene Schluckauf dauerte ___.", antwort: "68 Jahre" },
  { frage: "Oktopusse haben ___ Gehirne.", antwort: "neun" },
  { frage: "In Norwegen wurde ein Pinguin offiziell ___.", antwort: "zum Ritter geschlagen" },
  { frage: "Der Eiffelturm wird im Sommer bis zu ___ grösser.", antwort: "15 Zentimeter" },
  { frage: "Wombats produzieren Kot in Form von ___.", antwort: "Würfeln" },
  { frage: "In einem japanischen Hotel arbeiten an der Rezeption ___.", antwort: "Roboter-Dinosaurier" },
  { frage: "Honig ist das einzige Lebensmittel, das ___.", antwort: "nie verdirbt" },
  { frage: "Der kürzeste Krieg der Geschichte dauerte nur ___.", antwort: "38 Minuten" },
  { frage: "Ein Blitz ist etwa ___ heiss.", antwort: "fünfmal so heiss wie die Sonnenoberfläche" },
  { frage: "In Frankreich war es lange verboten, ein Schwein ___.", antwort: "im Restaurant mitzunehmen" },
  { frage: "Schmetterlinge schmecken mit ___.", antwort: "ihren Füssen" },
  { frage: "In Island gibt es keine ___.", antwort: "Mücken" },
  { frage: "Der erste Wecker der Welt konnte nur ___ klingeln.", antwort: "um vier Uhr morgens" },
  { frage: "Ein Faultier braucht bis zu ___, um eine Mahlzeit zu verdauen.", antwort: "einen Monat" },
  { frage: "In Bhutan misst die Regierung offiziell das ___.", antwort: "Bruttonationalglück" },
  { frage: "Erdnüsse sind botanisch gesehen keine Nüsse, sondern ___.", antwort: "Hülsenfrüchte" },
  { frage: "Die Zunge eines Blauwals wiegt ungefähr so viel wie ___.", antwort: "ein Elefant" },
  { frage: "In Australien gibt es mehr ___ als Menschen.", antwort: "Kängurus" },
  { frage: "Der Geruch von frisch geschnittenem Gras ist eigentlich ___.", antwort: "ein Hilferuf der Pflanze" },
  { frage: "In Dänemark ist es Tradition, Unverheiratete an ihrem 25. Geburtstag mit ___ zu bewerfen.", antwort: "Zimt" },
  { frage: "Ein Tag auf der Venus dauert länger als ___.", antwort: "ein Jahr auf der Venus" },
  { frage: "Die meisten Menschen verbringen insgesamt etwa ___ ihres Lebens am Handy.", antwort: "vier Jahre" },
  { frage: "In Singapur ist es verboten, ___ zu verkaufen.", antwort: "Kaugummi" },
  { frage: "Delfine geben sich gegenseitig ___.", antwort: "Namen" },
  { frage: "Der grösste je gebaute Burger wog etwa ___.", antwort: "eine halbe Tonne" },
  { frage: "In der Schweiz ist es verboten, ein Meerschweinchen ___.", antwort: "allein zu halten" },
  { frage: "Katzen können bis zu ___ verschiedene Laute machen.", antwort: "hundert" },
  { frage: "Der erste Computerbug war tatsächlich ___.", antwort: "eine echte Motte" },
  { frage: "In Russland gilt Bier bis 2011 offiziell nicht als Alkohol, sondern als ___.", antwort: "Lebensmittel" },
  { frage: "Ein Niesen verlässt die Nase mit etwa ___.", antwort: "160 Stundenkilometern" },
  { frage: "Die Erde ist an ihrer dicksten Stelle ___.", antwort: "am Äquator" },
  { frage: "In Ägypten wurden Katzen früher offiziell ___.", antwort: "einbalsamiert wie Menschen" },
  { frage: "Der Mensch teilt etwa ___ seiner DNA mit einer Banane.", antwort: "60 Prozent" },
  { frage: "In manchen Teilen Chinas gilt es als Glück, ___ zu essen.", antwort: "lange Nudeln ohne abzubeissen" },
  { frage: "Eine Giraffe schläft pro Tag nur etwa ___.", antwort: "30 Minuten" },
  { frage: "Der teuerste Pilz der Welt kostet pro Kilo bis zu ___.", antwort: "5000 Franken" },
  { frage: "In Neuseeland gibt es einen Ort mit einem Namen aus ___ Buchstaben.", antwort: "85" },
  { frage: "Rote Haare kommen bei etwa ___ der Weltbevölkerung vor.", antwort: "zwei Prozent" },
  { frage: "Ein Krokodil kann seine ___ nicht bewegen.", antwort: "Zunge" },
  { frage: "In Japan gibt es Automaten, aus denen man ___ ziehen kann.", antwort: "warme Suppe" },
  { frage: "Die grösste je gemessene Schneeflocke war etwa ___ breit.", antwort: "38 Zentimeter" },
  { frage: "Papier kann man theoretisch nur ___ in der Mitte falten.", antwort: "sieben Mal" },
  { frage: "In Mexiko gibt es eine Insel, die komplett voller ___ ist.", antwort: "Puppen" },
  { frage: "Ein Kaugummi braucht im Magen ungefähr ___, um zu verschwinden.", antwort: "genauso lang wie normales Essen" },
  { frage: "Die längste je gemessene Katze war etwa ___ lang.", antwort: "1,20 Meter" },
  { frage: "In den Niederlanden gibt es mehr ___ als Einwohner.", antwort: "Fahrräder" },
  { frage: "Ein Waschbär wäscht sein Essen nicht, sondern ___.", antwort: "ertastet es" },
  { frage: "Der erste Emoji wurde ursprünglich für ___ erfunden.", antwort: "Handys in Japan" },
  { frage: "Die durchschnittliche Person läuft im Leben etwa ___.", antwort: "dreimal um die Erde" },
  { frage: "In Schottland war es lange verboten, ___ zu sein.", antwort: "an einem Sonntag betrunken" },
  { frage: "Ein Elefant kann mit seinen ___ hören.", antwort: "Füssen" },
  { frage: "Die kürzeste je verzeichnete Flugverbindung dauert etwa ___.", antwort: "90 Sekunden" },
  { frage: "In Deutschland ist es verboten, auf der Autobahn ___.", antwort: "absichtlich das Benzin ausgehen zu lassen" },
  { frage: "Pandas verbringen täglich bis zu ___ mit Fressen.", antwort: "14 Stunden" },
  { frage: "Das menschliche Auge kann etwa ___ Farbnuancen unterscheiden.", antwort: "10 Millionen" }
];
