
const CATEGORIES = [
  { category: "Geruch", left: "Stinkt", right: "Riecht gut" },
  { category: "Bekanntheit", left: "Unbekannt", right: "Berühmt" },
  { category: "Preis", left: "Billig", right: "Teuer" },
  { category: "Geschwindigkeit", left: "Langsam", right: "Schnell" },
  { category: "Temperatur", left: "Kalt", right: "Heiss" },
  { category: "Grösse", left: "Winzig", right: "Riesig" },
  { category: "Gefahr", left: "Harmlos", right: "Tödlich" },
  { category: "Alter", left: "Jung", right: "Alt" },
  { category: "Lautstärke", left: "Leise", right: "Laut" },
  { category: "Geschmack", left: "Eklig", right: "Lecker" },
  { category: "Beliebtheit", left: "Unbeliebt", right: "Beliebt" },
  { category: "Schwierigkeit", left: "Einfach", right: "Schwer" },
  { category: "Helligkeit", left: "Dunkel", right: "Hell" },
  { category: "Gewicht", left: "Leicht", right: "Schwer" },
  { category: "Süsse", left: "Sauer", right: "Süss" },
  { category: "Härte", left: "Weich", right: "Hart" },
  { category: "Peinlichkeit", left: "Normal", right: "Peinlich" },
  { category: "Chaos", left: "Ordentlich", right: "Chaotisch" },
  { category: "Mut", left: "Feige", right: "Mutig" },
  { category: "Reichtum", left: "Arm", right: "Reich" },
  { category: "Nützlichkeit", left: "Nutzlos", right: "Unverzichtbar" },
  { category: "Peinlichkeit extrem", left: "Völlig normal", right: "Extrem peinlich" },
  { category: "Gesundheit", left: "Ungesund", right: "Sehr gesund" },
  { category: "Aufwand", left: "Mühelos", right: "Knochenarbeit" },
  { category: "Sucht", left: "Kein Suchtpotenzial", right: "Hochgradig süchtig" },
  { category: "Romantik", left: "Unromantisch", right: "Sehr romantisch" },
  { category: "Weichheit", left: "Steinhart", right: "Butterweich" },
  { category: "Helligkeit extrem", left: "Stockdunkel", right: "Blendend hell" },
  { category: "Ordnung", left: "Chaotisch", right: "Pedantisch ordentlich" },
  { category: "Süsse extrem", left: "Bitter", right: "Zuckersüss" },
  { category: "Nostalgie", left: "Brandneu", right: "Reine Nostalgie" },
  { category: "Gruselfaktor", left: "Harmlos", right: "Albtraumhaft" },
  { category: "Sinnhaftigkeit", left: "Sinnlos", right: "Absolut sinnvoll" },
  { category: "Sättigung", left: "Macht nicht satt", right: "Pappsatt" },
  { category: "Fahrtauglichkeit", left: "Steht nur rum", right: "Rennmaschine" },
  { category: "Aufmerksamkeit", left: "Übersieht man", right: "Fällt sofort auf" },
  { category: "Schwierigkeit beim Aussprechen", left: "Kinderleicht", right: "Zungenbrecher" },
  { category: "Gewicht extrem", left: "Federleicht", right: "Bleischwer" },
  { category: "Haltbarkeit", left: "Sofort verdorben", right: "Ewig haltbar" },
  { category: "Kindertauglichkeit", left: "Nur für Erwachsene", right: "Perfekt für Kinder" },
  { category: "Sauberkeit", left: "Dreckig", right: "Blitzblank" },
  { category: "Anstrengung beim Lernen", left: "Lernt man nebenbei", right: "Jahrelanges Üben" },
  { category: "Gesprächsstoff", left: "Todlangweilig", right: "Stundenlang Thema" },
  { category: "Verlässlichkeit", left: "Fällt ständig aus", right: "Läuft immer" },
  { category: "Stärke des Geruchs", left: "Geruchlos", right: "Riecht meilenweit" },
  { category: "Verletzungsgefahr", left: "Völlig sicher", right: "Sehr gefährlich" },
  { category: "Platzbedarf", left: "Passt in die Tasche", right: "Braucht eine Halle" },
  { category: "Lernkurve", left: "Sofort verstanden", right: "Nie ganz durchschaut" },
  { category: "Umweltfreundlichkeit", left: "Umweltsünde", right: "Komplett nachhaltig" },
  { category: "Stimmungsaufheller", left: "Deprimierend", right: "Macht sofort gute Laune" },
  { category: "Wartezeit", left: "Sofort verfügbar", right: "Monatelang warten" },
  { category: "Komplexität", left: "Simpel", right: "Hochkomplex" },
  { category: "Prestige", left: "Peinlich zu erwähnen", right: "Beeindruckt jeden" },
  { category: "Nervfaktor", left: "Angenehm", right: "Unerträglich nervig" },
  { category: "Wärme", left: "Eiskalt", right: "Glühend heiss" },
  { category: "Verbreitung", left: "Kennt kaum jemand", right: "Kennt jeder" },
  { category: "Handlichkeit", left: "Sperrig", right: "Passt in eine Hand" },
  { category: "Suchtgefahr beim Essen", left: "Ein Stück reicht", right: "Packung leer" },
  { category: "Reparierbarkeit", left: "Wegwerfen", right: "Ewig reparierbar" },
  { category: "Lautstärke im Betrieb", left: "Flüsterleise", right: "Ohrenbetäubend" }
];
