const RAETSEL = [
  // FILME
  { emojis: ["🚢", "🧊", "💔", "🌊"], antwort: "Titanic" },
  { emojis: ["🦁", "👑", "🐗", "🐒"], antwort: "Der König der Löwen" },
  { emojis: ["⚡", "🧙", "🦉", "🚂"], antwort: "Harry Potter" },
  { emojis: ["💍", "🌋", "🧙", "🧝"], antwort: "Der Herr der Ringe" },
  { emojis: ["⭐", "⚔️", "🤖", "🚀"], antwort: "Star Wars" },
  { emojis: ["🏴‍☠️", "⚓", "💀", "🧭"], antwort: "Fluch der Karibik" },
  { emojis: ["🦖", "🏝️", "🧬", "🚙"], antwort: "Jurassic Park" },
  { emojis: ["🚗", "⚡", "🕰️", "🔥"], antwort: "Zurück in die Zukunft" },
  { emojis: ["🚀", "🌽", "🕳️", "⌚"], antwort: "Interstellar" },
  { emojis: ["💊", "🕶️", "🐇", "💻"], antwort: "Matrix" },
  { emojis: ["🛡️", "🔨", "🤖", "💚"], antwort: "The Avengers" },
  { emojis: ["🕷️", "🕸️", "🏙️", "🦸"], antwort: "Spider-Man" },
  { emojis: ["🦇", "🃏", "🌃", "💣"], antwort: "The Dark Knight" },
  { emojis: ["👻", "🚫", "🚒", "🏙️"], antwort: "Ghostbusters" },
  { emojis: ["👽", "📞", "🚲", "🌕"], antwort: "E.T." },
  { emojis: ["🍫", "🏃", "🪶", "🚌"], antwort: "Forrest Gump" },
  { emojis: ["🤡", "🎈", "🚲", "🕳️"], antwort: "Es" },
  { emojis: ["❄️", "👸", "⛄", "🦌"], antwort: "Die Eiskönigin" },
  { emojis: ["👠", "🎃", "🕛", "🏰"], antwort: "Cinderella" },
  { emojis: ["🐼", "🥋", "🍜", "🐉"], antwort: "Kung Fu Panda" },
  { emojis: ["🧌", "🐴", "👸", "🐉"], antwort: "Shrek" },
  { emojis: ["🐠", "🔎", "🌊", "🐢"], antwort: "Findet Nemo" },
  { emojis: ["🎈", "🏠", "👴", "🐦"], antwort: "Oben" },
  { emojis: ["🤠", "🚀", "🧸", "👦"], antwort: "Toy Story" },
  { emojis: ["🚗", "⚡", "🏁", "🏆"], antwort: "Cars" },
  { emojis: ["👽", "🕶️", "🔫", "🧠"], antwort: "Men in Black" },
  { emojis: ["🦈", "🌊", "🚤", "🏖️"], antwort: "Der weiße Hai" },
  { emojis: ["🥊", "🥩", "🏃", "🪜"], antwort: "Rocky" },
  { emojis: ["🦍", "🏙️", "🏢", "✈️"], antwort: "King Kong" },
  { emojis: ["👨‍🚀", "🔴", "🥔", "🌱"], antwort: "Der Marsianer" },

  // SERIEN
  { emojis: ["🐉", "❄️", "👑", "⚔️"], antwort: "Game of Thrones" },
  { emojis: ["🧪", "💎", "🎩", "🚐"], antwort: "Breaking Bad" },
  { emojis: ["☕", "🛋️", "🦞", "🏙️"], antwort: "Friends" },
  { emojis: ["🏢", "📄", "📎", "☕"], antwort: "The Office" },
  { emojis: ["👹", "🚲", "🧇", "🔦"], antwort: "Stranger Things" },
  { emojis: ["🦑", "🔴", "🟢", "💰"], antwort: "Squid Game" },
  { emojis: ["🏦", "🎭", "🔴", "🇪🇸"], antwort: "Haus des Geldes" },
  { emojis: ["🟡", "🍩", "🍺", "🏭"], antwort: "Die Simpsons" },
  { emojis: ["🧽", "🍍", "🍔", "⭐"], antwort: "SpongeBob Schwammkopf" },
  { emojis: ["👑", "🇬🇧", "🏰", "💂"], antwort: "The Crown" },
  { emojis: ["🧟", "🔫", "🛣️", "🏚️"], antwort: "The Walking Dead" },
  { emojis: ["🏥", "🩺", "❤️", "👩‍⚕️"], antwort: "Grey's Anatomy" },
  { emojis: ["🕵️", "🔍", "🎻", "🇬🇧"], antwort: "Sherlock" },
  { emojis: ["⚛️", "🤓", "🚪", "🚂"], antwort: "The Big Bang Theory" },
  { emojis: ["👨‍👩‍👧‍👦", "🍺", "🐶", "👶"], antwort: "Family Guy" },
  { emojis: ["🩸", "🔪", "🌴", "🚤"], antwort: "Dexter" },
  { emojis: ["🖤", "✋", "🏫", "🕷️"], antwort: "Wednesday" },
  { emojis: ["🏝️", "✈️", "4️⃣", "8️⃣"], antwort: "Lost" },
  { emojis: ["👔", "⚖️", "💼", "🏙️"], antwort: "Suits" },
  { emojis: ["👮", "🚔", "😂", "9️⃣9️⃣"], antwort: "Brooklyn Nine-Nine" },

  // BERÜHMTE SCHAUSPIELER
  { emojis: ["🚢", "🧊", "🌀", "🐻"], antwort: "Leonardo DiCaprio" },
  { emojis: ["🏴‍☠️", "🍫", "✂️", "🎩"], antwort: "Johnny Depp" },
  { emojis: ["🪨", "💪", "🤨", "🌴"], antwort: "Dwayne Johnson" },
  { emojis: ["✈️", "🏍️", "🕶️", "🏃"], antwort: "Tom Cruise" },
  { emojis: ["🤖", "🔫", "💪", "🇦🇹"], antwort: "Arnold Schwarzenegger" },
  { emojis: ["👽", "🕶️", "👊", "🧞"], antwort: "Will Smith" },
  { emojis: ["🕷️", "💃", "🎾", "🖤"], antwort: "Zendaya" },
  { emojis: ["🦇", "🃏", "🏎️", "🇬🇧"], antwort: "Christian Bale" },
  { emojis: ["🔨", "⚡", "🌈", "🇦🇺"], antwort: "Chris Hemsworth" },
  { emojis: ["🛡️", "🇺🇸", "🦸", "🧊"], antwort: "Chris Evans" },

  // BERÜHMTE MUSIKER
  { emojis: ["🧤", "🌙", "🕺", "👑"], antwort: "Michael Jackson" },
  { emojis: ["👑", "🎸", "🕺", "🎰"], antwort: "Elvis Presley" },
  { emojis: ["🐝", "👑", "🍋", "💍"], antwort: "Beyoncé" },
  { emojis: ["1️⃣3️⃣", "🐍", "🧣", "🎤"], antwort: "Taylor Swift" },
  { emojis: ["☂️", "💎", "🇧🇧", "🎤"], antwort: "Rihanna" },
  { emojis: ["👋", "2️⃣1️⃣", "🇬🇧", "🎤"], antwort: "Adele" },
  { emojis: ["7️⃣", "💍", "🐈", "☁️"], antwort: "Ariana Grande" },
  { emojis: ["🌃", "🕶️", "🇨🇦", "🎤"], antwort: "The Weeknd" },
  { emojis: ["➗", "🎸", "🧡", "🇬🇧"], antwort: "Ed Sheeran" },
  { emojis: ["👶", "💜", "🇨🇦", "🎤"], antwort: "Justin Bieber" }
];
