
const RAETSEL = [
  // ===== Anime (sehr, sehr bekannt) =====
  { emojis: ["🏴‍☠️", "👒", "🍖", "🌊"], antwort: "One Piece" },
  { emojis: ["🍜", "🦊", "🥷", "🍥"], antwort: "Naruto" },
  { emojis: ["👊", "💥", "🟡", "🐉"], antwort: "Dragon Ball" },
  { emojis: ["🗡️", "🧱", "🏃", "👹"], antwort: "Attack on Titan" },
  { emojis: ["⚡", "📓", "💀", "🍎"], antwort: "Death Note" },
  { emojis: ["🔥", "🌊", "👺", "🗡️"], antwort: "Demon Slayer" },
  { emojis: ["👊", "💚", "🦸", "🎓"], antwort: "My Hero Academia" },
  { emojis: ["🍩", "😴", "👻", "⚡"], antwort: "Jujutsu Kaisen" },
  { emojis: ["⚗️", "🤖", "🦾", "💀"], antwort: "Fullmetal Alchemist" },
  { emojis: ["🎮", "⚔️", "💀", "🌐"], antwort: "Sword Art Online" },
  { emojis: ["🧪", "🔫", "🦋", "🕰️"], antwort: "Tokyo Ghoul" },
  { emojis: ["🎯", "🃏", "🗼", "🐸"], antwort: "Hunter x Hunter" },
  { emojis: ["👊", "🦸", "🥚", "💥"], antwort: "One Punch Man" },
  { emojis: ["🕵️", "🧠", "👧", "🔫"], antwort: "Spy x Family" },
  { emojis: ["🎸", "🎤", "🩸", "😈"], antwort: "Chainsaw Man" },
  { emojis: ["🐈", "💰", "🎩", "🌍"], antwort: "Cowboy Bebop" },
  { emojis: ["👁️‍🗨️", "⚔️", "🌙", "👹"], antwort: "Bleach" },
  { emojis: ["🔴", "⚪", "⚡", "🎒"], antwort: "Pokémon" },
  { emojis: ["🌙", "🎀", "😺", "✨"], antwort: "Sailor Moon" },
  { emojis: ["🎭", "🤖", "👁️", "🏫"], antwort: "Code Geass" },
  { emojis: ["🤖", "👦", "🌆", "🩸"], antwort: "Evangelion" },
  { emojis: ["✨", "🐉", "💍", "🗻"], antwort: "Fairy Tail" },
  { emojis: ["🍀", "⚔️", "🧙", "👑"], antwort: "Black Clover" },
  { emojis: ["⚔️", "🛶", "❄️", "🪓"], antwort: "Vinland Saga" },
  { emojis: ["⚔️", "🩸", "👹", "🖤"], antwort: "Berserk" },
  { emojis: ["🧛", "🌟", "😱", "💀"], antwort: "JoJo's Bizarre Adventure" },
  { emojis: ["7️⃣", "😈", "👑", "🍺"], antwort: "The Seven Deadly Sins" },
  { emojis: ["🏐", "🐦", "🏫", "🔥"], antwort: "Haikyuu" },
  { emojis: ["🏀", "🔴", "🏫", "👟"], antwort: "Slam Dunk" },
  { emojis: ["👹", "🗡️", "🌙", "🔔"], antwort: "Inuyasha" },
  { emojis: ["🕰️", "🚪", "🔬", "🌀"], antwort: "Steins Gate" },
  { emojis: ["🐲", "🟠", "💥", "🦸‍♂️"], antwort: "Dragon Ball Super" },
  { emojis: ["🕵️", "👞", "💊", "🔍"], antwort: "Detektiv Conan" },
  { emojis: ["🥚", "🐉", "🧒", "💻"], antwort: "Digimon" },
  { emojis: ["🃏", "🎴", "🐉", "👑"], antwort: "Yu-Gi-Oh" },
  { emojis: ["🐷", "🏯", "👧", "👻"], antwort: "Chihiros Reise ins Zauberland" },
  { emojis: ["🐈", "🚌", "🌧️", "🌰"], antwort: "Mein Nachbar Totoro" },
  { emojis: ["🍞", "🔥", "🏰", "🧹"], antwort: "Das wandelnde Schloss" },
  { emojis: ["🐗", "🌲", "🏹", "👹"], antwort: "Prinzessin Mononoke" },
  { emojis: ["🐉", "🌊", "🐟", "👦"], antwort: "Ponyo" },
  { emojis: ["👣", "☄️", "🔗", "🌾"], antwort: "Your Name" },

  // ===== Ganz ganz berühmte Filme & Serien (Must-know) =====
  { emojis: ["⚡", "🧙", "🦉", "🚂"], antwort: "Harry Potter" },
  { emojis: ["💍", "🌋", "🧝", "🗡️"], antwort: "Herr der Ringe" },
  { emojis: ["🚀", "🌌", "⚔️", "🤖"], antwort: "Star Wars" },
  { emojis: ["🐉", "❄️", "👑", "⚔️"], antwort: "Game of Thrones" },
  { emojis: ["🧪", "💙", "🎩", "🚐"], antwort: "Breaking Bad" },
  { emojis: ["☕", "🛋️", "👫", "🏙️"], antwort: "Friends" },
  { emojis: ["🏢", "📎", "😐", "☕"], antwort: "The Office" },
  { emojis: ["👹", "🚲", "🧇", "🔦"], antwort: "Stranger Things" },
  { emojis: ["🦑", "🔴", "🟢", "💰"], antwort: "Squid Game" },
  { emojis: ["🏦", "🎭", "🔴", "🇪🇸"], antwort: "Haus des Geldes" },
  { emojis: ["🚢", "🧊", "💔", "🌊"], antwort: "Titanic" },
  { emojis: ["🦁", "👑", "🌅", "🐗"], antwort: "Der König der Löwen" },
  { emojis: ["🏴‍☠️", "⚓", "🦜", "💰"], antwort: "Fluch der Karibik" },
  { emojis: ["💊", "🕶️", "🐇", "💻"], antwort: "Matrix" },
  { emojis: ["🦸", "🛡️", "💥", "🌍"], antwort: "The Avengers" },
  { emojis: ["☢️", "🏭", "🟡", "🍩"], antwort: "Die Simpsons" },
  { emojis: ["🟨", "🔵", "🧽", "🍔"], antwort: "SpongeBob" },
  { emojis: ["🦖", "🏝️", "🧬", "🚙"], antwort: "Jurassic Park" },
  { emojis: ["🕰️", "🚗", "⚡", "🔙"], antwort: "Zurück in die Zukunft" },
  { emojis: ["🚀", "🌌", "⏳", "🕳️"], antwort: "Interstellar" }
];
