/* Quizduell: player controls embedded in the Host view. */
(function(){
  'use strict';
  if(new URLSearchParams(location.search).get('stream')==='1') return;
  let ready=false, name='';
  const $=id=>document.getElementById(id);
  const esc=s=>{const d=document.createElement('div');d.textContent=String(s||'');return d.innerHTML};
  function style(){if($('qdHostPlayerStyle'))return;const s=document.createElement('style');s.id='qdHostPlayerStyle';s.textContent=`
  #qdHostPlayer{position:fixed;right:18px;bottom:18px;width:min(330px,calc(100vw - 36px));z-index:9500;padding:14px 15px;border:1px solid rgba(255,255,255,.14);border-radius:20px;background:rgba(7,11,22,.95);backdrop-filter:blur(18px);box-shadow:0 20px 70px rgba(0,0,0,.5);font-family:Inter,system-ui,sans-serif;color:#eef1f8}
  #qdHostPlayer .top{display:flex;justify-content:space-between;align-items:center;gap:10px}#qdHostPlayer .ey{font-size:10px;letter-spacing:.16em;text-transform:uppercase;color:#8792aa;font-weight:900}#qdHostPlayer .pts{font-size:22px;font-weight:900;color:#ffd166}#qdHostPlayer input{width:100%;box-sizing:border-box;margin:10px 0;padding:12px 13px;border-radius:12px;border:1px solid #293552;background:#10182a;color:#fff;outline:none}#qdHostPlayer .row{display:flex;gap:8px}#qdHostPlayer button{flex:1;border:0;border-radius:12px;padding:12px;font-weight:900;color:#fff;background:#17223a;cursor:pointer}#qdHostPlayer button.primary{background:linear-gradient(135deg,#00e5c7,#5a78fa);color:#04120f}#qdHostPlayer button:disabled{opacity:.4;cursor:not-allowed}#qdHostPlayer .status{font-size:11px;color:#8994ac;margin:7px 0 9px}#qdHostPlayer .cam{width:100%;aspect-ratio:16/9;border-radius:14px;background:#05070d;object-fit:cover;display:none;margin-top:10px}
  `;document.head.appendChild(s)}
  function mount(){if(ready||!$('hostView'))return;ready=true;style();const p=document.createElement('aside');p.id='qdHostPlayer';p.innerHTML=`<div class="top"><div><div class="ey">Dein Spieler</div><div id="qdHPName">Noch nicht beigetreten</div></div><div class="pts" id="qdHPPts">0 P</div></div><input id="qdHPInput" maxlength="32" placeholder="Dein Name" autocomplete="nickname"><div class="status" id="qdHPStatus">Name eingeben und beitreten.</div><div class="row"><button class="primary" id="qdHPJoin">Beitreten</button></div><video id="qdHPCamVideo" class="cam" autoplay muted playsinline></video>`;document.body.appendChild(p);$('qdHPJoin').onclick=join;const saved=sessionStorage.getItem('quizduell_player_name')||'';if(saved){$('qdHPInput').value=saved;join(saved)}setInterval(render,350)}
  async function join(pre){const input=$('qdHPInput');const n=window.KA_PUBLIC?.normalizeName(pre||input.value);if(!n)return;const reg=await window.KA_PUBLIC.registerPlayer(n,'quizduell');if(!reg?.ok)return;name=n;let p=(players||[]).find(x=>x.name.toLowerCase()===n.toLowerCase());if(p&&reg.data?.fresh===true){const rr=await sb.from('quiz_players').update({score:0,cards:0,joker_used:false}).eq('id',p.id).select().single();if(rr.error)return;p=rr.data}if(!p){const r=await sb.from('quiz_players').insert({name:n,score:0,cards:0,joker_used:false}).select().single();if(r.error)return;p=r.data}myPlayerId=p.id;sessionStorage.setItem('quizduell_player_name',n);sessionStorage.setItem('quizduell_pid',p.id);$('qdHPInput').style.display='none';$('qdHPJoin').style.display='none';window.KA_PLAYER_HOST={score:()=>{const x=(players||[]).find(y=>y.id===myPlayerId);return Number(x?.score||0)},action:()=>window.pressBuzz?.()};render();if(window.KA_CAM)window.KA_CAM.init({format:'quizduell',name:n,role:'player'});}
    function render(){if(!ready||!name)return;const p=(players||[]).find(x=>x.id===myPlayerId||x.name===name);const st=$('qdHPStatus'),pts=$('qdHPPts');$('qdHPName').textContent=name;if(p)pts.textContent=(p.score||0)+' P';if(!state){st.textContent='Verbinde…';return}const locked=(state.already_buzzed||[]).includes(myPlayerId);const can=state.buzzer_open&&!state.buzzed_player_id&&!locked;st.textContent=can?'Buzzer offen · Steuerung in deiner Spielerkarte.':state.buzzed_player_id?'Buzzer ist belegt.':'Warte auf die nächste Frage.'}
  function boot(){const wait=setInterval(()=>{if(window.ROLE==='host'){clearInterval(wait);mount()}},100)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
